### ISSUE TITLE
FollowRedirects + Excon "TypeError: no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by dentarg** [lostisland/faraday_middleware#131] opened 2016-02-16 10:16 UTC
```ruby
$ pry
[1] pry(main)> RUBY_VERSION
=> "2.2.3"
[2] pry(main)> require "faraday"
=> true
[3] pry(main)> require "faraday_middleware"
=> true
[4] pry(main)> require "excon"
=> true
[5] pry(main)> Faraday::VERSION
=> "0.9.2"
[6] pry(main)> require "faraday_middleware/version"
=> true
[7] pry(main)> FaradayMiddleware::VERSION
=> "0.10.0"
[8] pry(main)> Excon::VERSION
=> "0.45.4"
[9] pry(main)> connection = Faraday.new do |faraday|
[9] pry(main)*   faraday.use FaradayMiddleware::FollowRedirects
[9] pry(main)*   faraday.adapter :excon
[9] pry(main)* end
=> #<Faraday::Connection:0x007fb053377908
 @builder=#<Faraday::RackBuilder:0x007fb053377520 @handlers=[FaradayMiddleware::FollowRedirects, Faraday::Adapter::Excon]>,
 @default_parallel_manager=nil,
 @headers={"User-Agent"=>"Faraday v0.9.2"},
 @options=#<struct Faraday::RequestOptions params_encoder=nil, proxy=nil, bind=nil, timeout=nil, open_timeout=nil, boundary=nil, oauth=nil>,
 @parallel_manager=nil,
 @params={},
 @proxy=nil,
 @ssl=
  #<struct Faraday::SSLOptions
   verify=nil,
   ca_file=nil,
   ca_path=nil,
   verify_mode=nil,
   cert_store=nil,
   client_cert=nil,
   client_key=nil,
   certificate=nil,
   private_key=nil,
   verify_depth=nil,
   version=nil>,
 @url_prefix=#<URI::HTTP http:/>>

[10] pry(main)> connection.head("http://www.notiflux.com")
TypeError: no implicit conversion of nil into String
from /Users/dentarg/.gem/ruby/2.2.3/gems/excon-0.45.4/lib/excon/connection.rb:89:in `initialize'

[11] pry(main)> wtf??
Exception: TypeError: no implicit conversion of nil into String
--
 0: /Users/dentarg/.gem/ruby/2.2.3/gems/excon-0.45.4/lib/excon/connection.rb:89:in `initialize'
 1: /Users/dentarg/.gem/ruby/2.2.3/gems/excon-0.45.4/lib/excon.rb:126:in `new'
 2: /Users/dentarg/.gem/ruby/2.2.3/gems/excon-0.45.4/lib/excon.rb:126:in `new'
 3: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/excon.rb:53:in `call'
 4: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
 5: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:82:in `block in perform_with_redirection'
 6: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
 7: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
 8: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
 9: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
10: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
11: /Users/dentarg/.gem/ruby/2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `head'
12: (pry):13:in `__pry__'
13: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `eval'
14: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
15: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:323:in `handle_line'
16: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
17: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `catch'
18: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `block in eval'
19: /Users/dentarg/.gem/ruby/2.2.3/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `catch'
```

Using Excon directly I get another exception (better, specific to Excon):

```ruby
[12] pry(main)> excon_connection = Excon.new("http://www.notiflux.com", middlewares: Excon.defaults[:middlewares] + [Excon::Middleware::RedirectFollower])
=> #<Excon::Connection:7fb053534f98 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.45.4"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock, Excon::Middleware::RedirectFollower], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-darwin14) ruby/2.2.3", :write_timeout=>60, :host=>"www.notiflux.com", :hostname=>"www.notiflux.com", :path=>"", :port=>80, :query=>nil, :scheme=>"http"} @socket_key="http://www.notiflux.com:80">
[13] pry(main)> excon_connection.head
Excon::Errors::SocketError: hostname "www.notiflux.com" does not match the server certificate (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
from /Users/dentarg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/openssl/ssl.rb:240:in `post_connection_check'
```

Yes, http://www.notiflux.com is obviously broken, it responds with `Location: https://`, but I think we should be able to handle broken sites.

```
$ curl -s -v -L  -o /dev/null http://www.notiflux.com
* Rebuilt URL to: http://www.notiflux.com/
*   Trying 104.130.212.218...
* Connected to www.notiflux.com (104.130.212.218) port 80 (#0)
> GET / HTTP/1.1
> Host: www.notiflux.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: https://
< Server: Microsoft-IIS/8.5
< X-Powered-By: ASP.NET
< Date: Tue, 16 Feb 2016 10:12:58 GMT
< Content-Length: 0
<
* Connection #0 to host www.notiflux.com left intact
* Issue another request to this URL: 'http://www.notiflux.com/https://'
* Found bundle for host www.notiflux.com: 0x7ffb8ac09d80
* Re-using existing connection! (#0) with host www.notiflux.com
* Connected to www.notiflux.com (104.130.212.218) port 80 (#0)
> GET /https:// HTTP/1.1
> Host: www.notiflux.com
> User-Agent: curl/7.43.0
> Accept: */*

...
```

Interestingly, `curl` treats the value from the `Location` header as relative. But that's another issue I guess... :)

**Comment by dentarg** [comment] 2016-10-13 11:30
Since we went from excon (0.46.0) -> excon (0.52.0), in the project where this came from, it seems like we no longer have this problem (I haven't verified, just putting it out there)

**Comment by iMacTia** [comment] 2016-10-13 11:33
Thanks @dentarg for the update and apologies if no one picked it up before.
Feel free to close this issue if you think that the issue is now gone.

**Comment by dentarg** [comment] 2016-10-13 16:30
We can close it, the domain above seems dead so unfortunately I have no repro now

**Closed** 2016-10-13 16:31 UTC
