### ISSUE TITLE
Gem hash difference

### ISSUE THREAD

**Issue by dalemy** [lostisland/faraday_middleware#165] opened 2017-08-03 11:23 UTC
I'm seeing a similar issue to https://github.com/bundler/bundler/issues/5332

Basically if I run `gem fetch faraday_middleware -v 0.12.1` then `shasum -a256 faraday_middleware-0.12.1.gem` the hash I see (021dc9fd7e7b6de1bc394637c7b8214a1f8b2d1407867e5239c90b5405a31ff3) is different than the one on rubygems.org (06764c0b5e7f10a5efeae501da2c825f0e479969c8ca9b585583fd6546ba63df).

Republishing seemed to help last time. Can we try again?

As a side note, seems a little odd that it happens to this gem twice but is a rare thing?

**Comment by beloso** [comment] 2017-08-03 11:26
I am having the same problem:

> (The expected SHA256 checksum was "06764c0b5e7f10a5efeae501da2c825f0e479969c8ca9b585583fd6546ba63df", but
the checksum for the downloaded gem was "021dc9fd7e7b6de1bc394637c7b8214a1f8b2d1407867e5239c90b5405a31ff3".)

**Comment by wojtha** [comment] 2017-08-03 12:51
Ran into this as well, it seems to be caused by Travis CI publishing process as @sonalkr132 [wrote](https://github.com/rubygems/rubygems.org/issues/1551#issuecomment-290924620):

> I believe we know why this is happening. You are using Travis to push gems. Travis ends pushing the gem from all the jobs. One of them pass and rest fail. Because of the race condition in Api::V1::RubygemsController#create, we end up with incorrect checksums.

**Comment by adellibovi** [comment] 2017-08-03 13:05
Exactly same problem here too
`(More info: The expected SHA256 checksum was
"06764c0b5e7f10a5efeae501da2c825f0e479969c8ca9b585583fd6546ba63df", but the
checksum for the downloaded gem was
"021dc9fd7e7b6de1bc394637c7b8214a1f8b2d1407867e5239c90b5405a31ff3".)`

**Comment by Zero3nna** [comment] 2017-08-03 13:26
Same problem for me if our Jenkins tries to `bundle update`

**Comment by iMacTia** [comment] 2017-08-03 15:16
I'm sorry guys this happened again, I thought this was fixed limiting the rubygems release to only some jobs. Clearly the fix is not working as expected, but it worked just fine for v0.12.0.
I'll try to get this fixed ASAP

**Comment by iMacTia** [comment] 2017-08-03 15:19
[this](https://github.com/lostisland/faraday_middleware/blob/master/.travis.yml#L26) is the condition I'm referring to, it should publish on Rubygems ONLY for the "2.4.0 / Gemfile" combination.
I'll keep looking around for a reason but any suggestion is really welcome

**Comment by iMacTia** [comment] 2017-08-03 15:23
I'll try to apply the fix from this https://github.com/rubygems/rubygems.org/issues/1551#issuecomment-290924620 and re-release

**Comment by iMacTia** [comment] 2017-08-03 15:40
v0.12.2 on its way, finger crossed 🤞

**Comment by adellibovi** [comment] 2017-08-03 15:41
Thanks a lot @iMacTia and absolutely no need to be sorry about this :)

**Comment by iMacTia** [comment] 2017-08-03 15:42
Thanks @adellibovi, and just to be extra safe I'm running tests for ruby 2.4.0 only against the base Gemfile. I don't want to see race conditions anymore!

**Comment by iMacTia** [comment] 2017-08-03 15:46
[faraday_middleware 0.12.2 released](https://rubygems.org/gems/faraday_middleware/versions/0.12.2)

A quick `gem install faraday_middleware` successfully installed v0.12.2 so hopefully this is now fixed 👍

**Closed by iMacTia** 2017-08-03 15:46 UTC
